volumes:
  db-store:
  psysh-store:

services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - ./src:/workspace
      - psysh-store:/root/.config/psysh
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-IaTEnTectaLiAtiEV}
    networks:
      - default

  web:
    container_name: 'web'
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - ./src:/workspace
    networks:
      - default

  db:
    container_name: 'db'
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-IaTEnTectaLiAtiEV}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-IaTEnTectaLiAtiEV}
    networks:
      - default


networks:
  default:
    name: external-web-infrastructure
    external: false